[theme]
primaryColor="#2ecc71"
backgroundColor="#e8f5e9"
secondaryBackgroundColor="#ffffff"
textColor="#2f4f4f"

[theme.alertColor]
warning = "#E74C3C"
success = "#2ECC71"
info = "#3498DB"

[theme.button]
primaryButtonColor = "#27AE60"
secondaryButtonColor = "#1ABC9C"
